### ISSUE TITLE
multiple cluster instances issue

### ISSUE THREAD

**Issue by JSReligion** [codename-/division#3]
Hi, i trying to setup multiple clusters ( http and websocket servers ) in one app, but after running second instance of division (new division()) the first one becomes my second configuration..
its a bug or its not possible to make few cluster configuration in one app?
To easy check that just need to shutdown one process of first cluster instance.. and app reload cluster from second one..
Os: win8.1
nodejs version: 4.2.6 

```
var async= require("async");`
var division= require('division');

// cluster global config
var clusterSize= require('os').cpus().length / 2;

async.series([
    function( callback ){
        var http = new division( { path: 'cluster/http.js', size: clusterSize } );
        // Configuration for development environment
        http.configure('development', () => {
            http.use('debug');
        });

        // Configuration for production environment
        http.configure('production', () => {
            http.enable('silent');
        });

        http.set('args', ['--http']);

        // Start your application as a cluster!
        http.run( () => callback() );
    },
    function( callback ){
        var ws = new division( { path: 'cluster/webs.js', size: 0 } );
        // Configuration for development environment
        ws.configure('development', () => {
            ws.use('debug');
        });

        // Configuration for production environment
        ws.configure('production', () => {
            ws.enable('silent');
        });

        ws.set('args', ['--websocket']);

        // Start your application as a cluster!
        ws.run( () => callback() );
    }
], ( e ) => {
    if( e )
        return console.error( e );
    console.log( "init" );
});
```

`

**Comment by setthase** [comment]
Unfortunately you can't run multiple clusters from one node instance. 
This is restriction of node itself: https://nodejs.org/api/cluster.html

The best thing you could do is to setup a [reverse proxy](https://en.wikipedia.org/wiki/Reverse_proxy) and run two instances of node with **division**.
For the reverse proxy you could use for example [nginx](https://www.nginx.com/resources/admin-guide/reverse-proxy/) or another node instance with [proxy module](https://www.npmjs.com/search?q=proxy).

**Comment by JSReligion** [comment]
Thank you for your fast response and also that is so sad restriction =(

**Comment by setthase** [comment]
This restriction is based on how the cluster internal works (it's base on _child_process_ module). 

If you don't want to run a reverse proxy you could also try [supervisord](http://supervisord.org/index.html). It's a tool very similar to **division** (but used for more advanced cases), and as it's not written in node it shouldn't have those restrictions. You can also mix both together - **supervisord** and **division**.

**Comment by JSReligion** [comment]
Thank you, i have to read this, but i already split websocket and http server on different launchers, also i found that its possible to spawn childrenProcess on cluster worker :) thats all i need :)

So now i have :)

```
http 
    >> worker
    >> worker
...
websocket
    >> worker
         >> childprocess
    >> worker
         >> childprocess
```

...
